/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import dao.ReservationDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Reservation;

/**
 *
 * @author Afrique#
 */
public class ReservationManagement extends javax.swing.JFrame {
DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form ReservationManagement
     */
    public ReservationManagement() {
        initComponents();
        addColumnTableHeader();
        addRowTableData();
        clearField();

    }
 private void addColumnTableHeader(){
        tableModel.addColumn(" ID");
        tableModel.addColumn("First Name");
        tableModel.addColumn("Last Name ID");
        tableModel.addColumn("Phone");
        tableModel.addColumn("Room Number ID");
        tableModel.addColumn("Address");
        jTable1.setModel(tableModel);
    }
    private void addRowTableData() {
        tableModel.setRowCount(0);
         ReservationDao dao = new ReservationDao();
        List<Reservation> Reservations = dao.allReservations();
        for(Reservation user : Reservations){
            tableModel.addRow(new Object[]{
                user.getId(),
                user.getFirstname(),
                user.getLastname(),
                user.getPhone(),
                user.getRoomprice(),
                user.getAddress()
            });
        }}
    private void clearField(){
        idText.setText("");
        firstnameText.setText("");
        lastnameText.setText("");
        phoneText.setText("");
        roompriceText.setText("");
        addressText.setText("");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        firstnameText = new javax.swing.JTextField();
        lastnameText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        roompriceText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        reflesh = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("Phone");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("RoomPrice");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));
        jPanel1.add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 175, -1));
        jPanel1.add(firstnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 175, -1));
        jPanel1.add(lastnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 175, -1));
        jPanel1.add(phoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 175, -1));
        jPanel1.add(roompriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 175, -1));
        jPanel1.add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 175, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reserve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 450, 220));

        reflesh.setBackground(new java.awt.Color(0, 0, 0));
        reflesh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reflesh.setForeground(new java.awt.Color(255, 255, 255));
        reflesh.setText("Clear");
        reflesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refleshActionPerformed(evt);
            }
        });
        jPanel1.add(reflesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        BackBtn.setBackground(new java.awt.Color(0, 0, 0));
        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        quitBtn.setBackground(new java.awt.Color(0, 0, 0));
        quitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quitBtn.setForeground(new java.awt.Color(255, 255, 255));
        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(quitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Place for Resevation");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/A.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(1118, 810));
        jLabel7.setMinimumSize(new java.awt.Dimension(1118, 810));
        jLabel7.setPreferredSize(new java.awt.Dimension(1118, 810));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(idText.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "All Field are required");
        }else if(idText.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, " id is Mandator","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }
        if (!Character.isUpperCase(firstnameText.getText().charAt(0))) {
    JOptionPane.showMessageDialog(this, "First name should start with a capital letter", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
         else if (!phoneText.getText().matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "Phone Number should be 10 digits", "Invalid Phone Number", JOptionPane.WARNING_MESSAGE);
          }
         
          double price = Double.parseDouble(roompriceText.getText().trim());

    if (price <= 25000) {
        JOptionPane.showMessageDialog(this, "Price must be greater than 25000", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
         
        else{
            // 2. check book id if has 3 characters
            if(idText.getText().length() ==3){
                // call the Model
                Reservation user = new Reservation();
                user.setId(Integer.parseInt(idText.getText()));
                user.setFirstname(firstnameText.getText());
                user.setLastname(lastnameText.getText());
                user.setPhone(phoneText.getText());
                user.setRoomprice(roompriceText.getText());
                user.setAddress(addressText.getText());
                // call dao
                ReservationDao dao = new ReservationDao();
                String feedBack = dao.createReservation(user);
                JOptionPane.showMessageDialog(this, feedBack);
                 addRowTableData();
            }else{
                JOptionPane.showMessageDialog(this, " Id should have min \n and max 3 characters","Book ID Length",JOptionPane.WARNING_MESSAGE);
            }
            
        }       
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if(idText.getText().trim().isEmpty()
            || firstnameText.getText().trim().isEmpty()
             ||lastnameText.getText().trim().isEmpty()
            || phoneText.getText().trim().isEmpty()
             || roompriceText.getText().trim().isEmpty()
            || addressText.getText().trim().isEmpty()){     
            JOptionPane.showMessageDialog(this, "All Field are required");
        }else{
           
                // call the Model
                Reservation user = new Reservation();
                user.setId(Integer.parseInt(idText.getText()));
                user.setFirstname(firstnameText.getText());
                user.setLastname(lastnameText.getText());
                user.setPhone(phoneText.getText());
                user.setRoomprice(roompriceText.getText());
                user.setAddress(addressText.getText());
                // call dao
                ReservationDao dao = new ReservationDao();
                String feedBack = dao.updateReservation(user);
                JOptionPane.showMessageDialog(this, feedBack);
                addRowTableData();
                 
            }
            
               
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(idText.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Book ID to delete is mandatory");
        
        }
        else{
            // 2. check book id if has 3 characters
            if(idText.getText().length() ==3){
                // call the Model
                Reservation user = new Reservation();
                user.setId(Integer.parseInt(idText.getText()));
                // call dao
                ReservationDao dao = new ReservationDao();
                String feedBack = dao.deleteReservation(user);
                if(feedBack !=null){
                    JOptionPane.showMessageDialog(this, "Data Deleted");
                    addRowTableData();
        }else{
            JOptionPane.showMessageDialog(this, "Data Not Deleted");
        }
                }
       
            
            
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void refleshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refleshActionPerformed
            clearField();       // TODO add your handling code here:
    }//GEN-LAST:event_refleshActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
  this.dispose();
         new Login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
  int result = JOptionPane.showConfirmDialog(this, "Do you really want to Ouit the system?", "Accept", JOptionPane.YES_NO_OPTION);
       if(result == JOptionPane.YES_OPTION){
           this.dispose(); 
       }// TODO add your handling code here:
    }//GEN-LAST:event_quitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField firstnameText;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastnameText;
    private javax.swing.JTextField phoneText;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton reflesh;
    private javax.swing.JTextField roompriceText;
    // End of variables declaration//GEN-END:variables
}
